# Generated by Django 3.1.4 on 2021-01-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_searchresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResults',
            new_name='SearchResult',
        ),
    ]
